### PR TITLE
adds instructions to CWA notebooks

### LINKED ISSUE #4: plot by state in Enforcements notebook doesn't work
Because it's using the `my_cd_npdes` variable, so it plots the Congressional District data.

Sorry I said the Enforcements notebook works! Just a minor thing to fix.

I can fix it when I add instructions....(just needs to be replaced with `npdes_data`

### PR DESCRIPTION
**Pull request by ericnost**
adds Jupyter Notebook instructions
formats notebooks
fixes plot of state data in enforcement and inspections notebooks

per edgi-govdata-archiving/EEW_Planning#61

### CODE REVIEW

**Comment by Frijol** [comment]
working to resolve merge conflicts

**Comment by amit1rrr** [comment]
Sorry to intrude but I noticed this PR contains Jupyter notebook files that are hard to review on GitHub due to the JSON diffs.

You might want to checkout [ReviewNB](https://www.reviewnb.com/), code review tool for notebooks. Provides visual diffs & commenting for Jupyter notebooks on GitHub. Completely free for open source repositories.

Disclaimer: I built ReviewNB

diff_and_commenting

**Comment by Frijol** [comment]
Thanks @amit1rrr, I'll check it out!

**Comment by ericnost** [comment]
Do we still want/need to merge these??? @Frijol @shansen5

**Comment by ericnost** [comment]
> Do we still want/need to merge these??? @Frijol @shansen5

It says "no conflicts" so I am going to merge.

**Pull request merged**
